# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oleg/Deep_learning/Thesis/MaskedCNN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oleg/Deep_learning/Thesis/MaskedCNN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Deep_learning/Thesis/MaskedCNN/CMakeFiles /home/oleg/Deep_learning/Thesis/MaskedCNN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Deep_learning/Thesis/MaskedCNN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named maskedcnnexe

# Build rule for target.
maskedcnnexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maskedcnnexe
.PHONY : maskedcnnexe

# fast build rule for target.
maskedcnnexe/fast:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/build
.PHONY : maskedcnnexe/fast

#=============================================================================
# Target rules for targets named maskedcnn

# Build rule for target.
maskedcnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maskedcnn
.PHONY : maskedcnn

# fast build rule for target.
maskedcnn/fast:
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/build
.PHONY : maskedcnn/fast

#=============================================================================
# Target rules for targets named testmaskedcnn

# Build rule for target.
testmaskedcnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testmaskedcnn
.PHONY : testmaskedcnn

# fast build rule for target.
testmaskedcnn/fast:
	$(MAKE) -f test/CMakeFiles/testmaskedcnn.dir/build.make test/CMakeFiles/testmaskedcnn.dir/build
.PHONY : testmaskedcnn/fast

src/Activation.o: src/Activation.cpp.o

.PHONY : src/Activation.o

# target to build an object file
src/Activation.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Activation.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Activation.cpp.o
.PHONY : src/Activation.cpp.o

src/Activation.i: src/Activation.cpp.i

.PHONY : src/Activation.i

# target to preprocess a source file
src/Activation.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Activation.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Activation.cpp.i
.PHONY : src/Activation.cpp.i

src/Activation.s: src/Activation.cpp.s

.PHONY : src/Activation.s

# target to generate assembly for a file
src/Activation.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Activation.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Activation.cpp.s
.PHONY : src/Activation.cpp.s

src/ConvOps.o: src/ConvOps.cpp.o

.PHONY : src/ConvOps.o

# target to build an object file
src/ConvOps.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/ConvOps.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/ConvOps.cpp.o
.PHONY : src/ConvOps.cpp.o

src/ConvOps.i: src/ConvOps.cpp.i

.PHONY : src/ConvOps.i

# target to preprocess a source file
src/ConvOps.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/ConvOps.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/ConvOps.cpp.i
.PHONY : src/ConvOps.cpp.i

src/ConvOps.s: src/ConvOps.cpp.s

.PHONY : src/ConvOps.s

# target to generate assembly for a file
src/ConvOps.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/ConvOps.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/ConvOps.cpp.s
.PHONY : src/ConvOps.cpp.s

src/ConvolutionalLayer.o: src/ConvolutionalLayer.cpp.o

.PHONY : src/ConvolutionalLayer.o

# target to build an object file
src/ConvolutionalLayer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/ConvolutionalLayer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/ConvolutionalLayer.cpp.o
.PHONY : src/ConvolutionalLayer.cpp.o

src/ConvolutionalLayer.i: src/ConvolutionalLayer.cpp.i

.PHONY : src/ConvolutionalLayer.i

# target to preprocess a source file
src/ConvolutionalLayer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/ConvolutionalLayer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/ConvolutionalLayer.cpp.i
.PHONY : src/ConvolutionalLayer.cpp.i

src/ConvolutionalLayer.s: src/ConvolutionalLayer.cpp.s

.PHONY : src/ConvolutionalLayer.s

# target to generate assembly for a file
src/ConvolutionalLayer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/ConvolutionalLayer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/ConvolutionalLayer.cpp.s
.PHONY : src/ConvolutionalLayer.cpp.s

src/DataLoader.o: src/DataLoader.cpp.o

.PHONY : src/DataLoader.o

# target to build an object file
src/DataLoader.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/DataLoader.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/DataLoader.cpp.o
.PHONY : src/DataLoader.cpp.o

src/DataLoader.i: src/DataLoader.cpp.i

.PHONY : src/DataLoader.i

# target to preprocess a source file
src/DataLoader.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/DataLoader.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/DataLoader.cpp.i
.PHONY : src/DataLoader.cpp.i

src/DataLoader.s: src/DataLoader.cpp.s

.PHONY : src/DataLoader.s

# target to generate assembly for a file
src/DataLoader.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/DataLoader.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/DataLoader.cpp.s
.PHONY : src/DataLoader.cpp.s

src/DropoutLayer.o: src/DropoutLayer.cpp.o

.PHONY : src/DropoutLayer.o

# target to build an object file
src/DropoutLayer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/DropoutLayer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/DropoutLayer.cpp.o
.PHONY : src/DropoutLayer.cpp.o

src/DropoutLayer.i: src/DropoutLayer.cpp.i

.PHONY : src/DropoutLayer.i

# target to preprocess a source file
src/DropoutLayer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/DropoutLayer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/DropoutLayer.cpp.i
.PHONY : src/DropoutLayer.cpp.i

src/DropoutLayer.s: src/DropoutLayer.cpp.s

.PHONY : src/DropoutLayer.s

# target to generate assembly for a file
src/DropoutLayer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/DropoutLayer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/DropoutLayer.cpp.s
.PHONY : src/DropoutLayer.cpp.s

src/EltwiseLayer.o: src/EltwiseLayer.cpp.o

.PHONY : src/EltwiseLayer.o

# target to build an object file
src/EltwiseLayer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/EltwiseLayer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/EltwiseLayer.cpp.o
.PHONY : src/EltwiseLayer.cpp.o

src/EltwiseLayer.i: src/EltwiseLayer.cpp.i

.PHONY : src/EltwiseLayer.i

# target to preprocess a source file
src/EltwiseLayer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/EltwiseLayer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/EltwiseLayer.cpp.i
.PHONY : src/EltwiseLayer.cpp.i

src/EltwiseLayer.s: src/EltwiseLayer.cpp.s

.PHONY : src/EltwiseLayer.s

# target to generate assembly for a file
src/EltwiseLayer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/EltwiseLayer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/EltwiseLayer.cpp.s
.PHONY : src/EltwiseLayer.cpp.s

src/FullyConnectedLayer.o: src/FullyConnectedLayer.cpp.o

.PHONY : src/FullyConnectedLayer.o

# target to build an object file
src/FullyConnectedLayer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/FullyConnectedLayer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/FullyConnectedLayer.cpp.o
.PHONY : src/FullyConnectedLayer.cpp.o

src/FullyConnectedLayer.i: src/FullyConnectedLayer.cpp.i

.PHONY : src/FullyConnectedLayer.i

# target to preprocess a source file
src/FullyConnectedLayer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/FullyConnectedLayer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/FullyConnectedLayer.cpp.i
.PHONY : src/FullyConnectedLayer.cpp.i

src/FullyConnectedLayer.s: src/FullyConnectedLayer.cpp.s

.PHONY : src/FullyConnectedLayer.s

# target to generate assembly for a file
src/FullyConnectedLayer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/FullyConnectedLayer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/FullyConnectedLayer.cpp.s
.PHONY : src/FullyConnectedLayer.cpp.s

src/InputLayer.o: src/InputLayer.cpp.o

.PHONY : src/InputLayer.o

# target to build an object file
src/InputLayer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/InputLayer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/InputLayer.cpp.o
.PHONY : src/InputLayer.cpp.o

src/InputLayer.i: src/InputLayer.cpp.i

.PHONY : src/InputLayer.i

# target to preprocess a source file
src/InputLayer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/InputLayer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/InputLayer.cpp.i
.PHONY : src/InputLayer.cpp.i

src/InputLayer.s: src/InputLayer.cpp.s

.PHONY : src/InputLayer.s

# target to generate assembly for a file
src/InputLayer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/InputLayer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/InputLayer.cpp.s
.PHONY : src/InputLayer.cpp.s

src/Layer.o: src/Layer.cpp.o

.PHONY : src/Layer.o

# target to build an object file
src/Layer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Layer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Layer.cpp.o
.PHONY : src/Layer.cpp.o

src/Layer.i: src/Layer.cpp.i

.PHONY : src/Layer.i

# target to preprocess a source file
src/Layer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Layer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Layer.cpp.i
.PHONY : src/Layer.cpp.i

src/Layer.s: src/Layer.cpp.s

.PHONY : src/Layer.s

# target to generate assembly for a file
src/Layer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Layer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Layer.cpp.s
.PHONY : src/Layer.cpp.s

src/LayerLoader.o: src/LayerLoader.cpp.o

.PHONY : src/LayerLoader.o

# target to build an object file
src/LayerLoader.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/LayerLoader.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/LayerLoader.cpp.o
.PHONY : src/LayerLoader.cpp.o

src/LayerLoader.i: src/LayerLoader.cpp.i

.PHONY : src/LayerLoader.i

# target to preprocess a source file
src/LayerLoader.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/LayerLoader.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/LayerLoader.cpp.i
.PHONY : src/LayerLoader.cpp.i

src/LayerLoader.s: src/LayerLoader.cpp.s

.PHONY : src/LayerLoader.s

# target to generate assembly for a file
src/LayerLoader.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/LayerLoader.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/LayerLoader.cpp.s
.PHONY : src/LayerLoader.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Network.o: src/Network.cpp.o

.PHONY : src/Network.o

# target to build an object file
src/Network.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Network.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Network.cpp.o
.PHONY : src/Network.cpp.o

src/Network.i: src/Network.cpp.i

.PHONY : src/Network.i

# target to preprocess a source file
src/Network.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Network.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Network.cpp.i
.PHONY : src/Network.cpp.i

src/Network.s: src/Network.cpp.s

.PHONY : src/Network.s

# target to generate assembly for a file
src/Network.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Network.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Network.cpp.s
.PHONY : src/Network.cpp.s

src/PoolLayer.o: src/PoolLayer.cpp.o

.PHONY : src/PoolLayer.o

# target to build an object file
src/PoolLayer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/PoolLayer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/PoolLayer.cpp.o
.PHONY : src/PoolLayer.cpp.o

src/PoolLayer.i: src/PoolLayer.cpp.i

.PHONY : src/PoolLayer.i

# target to preprocess a source file
src/PoolLayer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/PoolLayer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/PoolLayer.cpp.i
.PHONY : src/PoolLayer.cpp.i

src/PoolLayer.s: src/PoolLayer.cpp.s

.PHONY : src/PoolLayer.s

# target to generate assembly for a file
src/PoolLayer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/PoolLayer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/PoolLayer.cpp.s
.PHONY : src/PoolLayer.cpp.s

src/SoftmaxLayer.o: src/SoftmaxLayer.cpp.o

.PHONY : src/SoftmaxLayer.o

# target to build an object file
src/SoftmaxLayer.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/SoftmaxLayer.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/SoftmaxLayer.cpp.o
.PHONY : src/SoftmaxLayer.cpp.o

src/SoftmaxLayer.i: src/SoftmaxLayer.cpp.i

.PHONY : src/SoftmaxLayer.i

# target to preprocess a source file
src/SoftmaxLayer.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/SoftmaxLayer.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/SoftmaxLayer.cpp.i
.PHONY : src/SoftmaxLayer.cpp.i

src/SoftmaxLayer.s: src/SoftmaxLayer.cpp.s

.PHONY : src/SoftmaxLayer.s

# target to generate assembly for a file
src/SoftmaxLayer.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/SoftmaxLayer.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/SoftmaxLayer.cpp.s
.PHONY : src/SoftmaxLayer.cpp.s

src/Training.o: src/Training.cpp.o

.PHONY : src/Training.o

# target to build an object file
src/Training.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Training.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Training.cpp.o
.PHONY : src/Training.cpp.o

src/Training.i: src/Training.cpp.i

.PHONY : src/Training.i

# target to preprocess a source file
src/Training.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Training.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Training.cpp.i
.PHONY : src/Training.cpp.i

src/Training.s: src/Training.cpp.s

.PHONY : src/Training.s

# target to generate assembly for a file
src/Training.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Training.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Training.cpp.s
.PHONY : src/Training.cpp.s

src/Visuals.o: src/Visuals.cpp.o

.PHONY : src/Visuals.o

# target to build an object file
src/Visuals.cpp.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Visuals.cpp.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Visuals.cpp.o
.PHONY : src/Visuals.cpp.o

src/Visuals.i: src/Visuals.cpp.i

.PHONY : src/Visuals.i

# target to preprocess a source file
src/Visuals.cpp.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Visuals.cpp.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Visuals.cpp.i
.PHONY : src/Visuals.cpp.i

src/Visuals.s: src/Visuals.cpp.s

.PHONY : src/Visuals.s

# target to generate assembly for a file
src/Visuals.cpp.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/Visuals.cpp.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/Visuals.cpp.s
.PHONY : src/Visuals.cpp.s

src/caffe.pb.o: src/caffe.pb.cc.o

.PHONY : src/caffe.pb.o

# target to build an object file
src/caffe.pb.cc.o:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/caffe.pb.cc.o
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/caffe.pb.cc.o
.PHONY : src/caffe.pb.cc.o

src/caffe.pb.i: src/caffe.pb.cc.i

.PHONY : src/caffe.pb.i

# target to preprocess a source file
src/caffe.pb.cc.i:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/caffe.pb.cc.i
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/caffe.pb.cc.i
.PHONY : src/caffe.pb.cc.i

src/caffe.pb.s: src/caffe.pb.cc.s

.PHONY : src/caffe.pb.s

# target to generate assembly for a file
src/caffe.pb.cc.s:
	$(MAKE) -f CMakeFiles/maskedcnnexe.dir/build.make CMakeFiles/maskedcnnexe.dir/src/caffe.pb.cc.s
	$(MAKE) -f CMakeFiles/maskedcnn.dir/build.make CMakeFiles/maskedcnn.dir/src/caffe.pb.cc.s
.PHONY : src/caffe.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... maskedcnnexe"
	@echo "... maskedcnn"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testmaskedcnn"
	@echo "... src/Activation.o"
	@echo "... src/Activation.i"
	@echo "... src/Activation.s"
	@echo "... src/ConvOps.o"
	@echo "... src/ConvOps.i"
	@echo "... src/ConvOps.s"
	@echo "... src/ConvolutionalLayer.o"
	@echo "... src/ConvolutionalLayer.i"
	@echo "... src/ConvolutionalLayer.s"
	@echo "... src/DataLoader.o"
	@echo "... src/DataLoader.i"
	@echo "... src/DataLoader.s"
	@echo "... src/DropoutLayer.o"
	@echo "... src/DropoutLayer.i"
	@echo "... src/DropoutLayer.s"
	@echo "... src/EltwiseLayer.o"
	@echo "... src/EltwiseLayer.i"
	@echo "... src/EltwiseLayer.s"
	@echo "... src/FullyConnectedLayer.o"
	@echo "... src/FullyConnectedLayer.i"
	@echo "... src/FullyConnectedLayer.s"
	@echo "... src/InputLayer.o"
	@echo "... src/InputLayer.i"
	@echo "... src/InputLayer.s"
	@echo "... src/Layer.o"
	@echo "... src/Layer.i"
	@echo "... src/Layer.s"
	@echo "... src/LayerLoader.o"
	@echo "... src/LayerLoader.i"
	@echo "... src/LayerLoader.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Network.o"
	@echo "... src/Network.i"
	@echo "... src/Network.s"
	@echo "... src/PoolLayer.o"
	@echo "... src/PoolLayer.i"
	@echo "... src/PoolLayer.s"
	@echo "... src/SoftmaxLayer.o"
	@echo "... src/SoftmaxLayer.i"
	@echo "... src/SoftmaxLayer.s"
	@echo "... src/Training.o"
	@echo "... src/Training.i"
	@echo "... src/Training.s"
	@echo "... src/Visuals.o"
	@echo "... src/Visuals.i"
	@echo "... src/Visuals.s"
	@echo "... src/caffe.pb.o"
	@echo "... src/caffe.pb.i"
	@echo "... src/caffe.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

